
/* !!! This is code generated by Prisma. Do not edit directly. !!!
/* eslint-disable */
// biome-ignore-all lint: generated file

Object.defineProperty(exports, "__esModule", { value: true });

const {
  Decimal,
  objectEnumValues,
  makeStrictEnum,
  Public,
  getRuntime,
  skip
} = require('./runtime/index-browser.js')


const Prisma = {}

exports.Prisma = Prisma
exports.$Enums = {}

/**
 * Prisma Client JS version: 6.19.2
 * Query Engine version: c2990dca591cba766e3b7ef5d9e8a84796e47ab7
 */
Prisma.prismaVersion = {
  client: "6.19.2",
  engine: "c2990dca591cba766e3b7ef5d9e8a84796e47ab7"
}

Prisma.PrismaClientKnownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientKnownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)};
Prisma.PrismaClientUnknownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientUnknownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientRustPanicError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientRustPanicError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientInitializationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientInitializationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientValidationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientValidationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.Decimal = Decimal

/**
 * Re-export of sql-template-tag
 */
Prisma.sql = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`sqltag is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.empty = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`empty is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.join = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`join is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.raw = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`raw is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.validator = Public.validator

/**
* Extensions
*/
Prisma.getExtensionContext = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.getExtensionContext is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.defineExtension = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.defineExtension is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}

/**
 * Shorthand utilities for JSON filtering
 */
Prisma.DbNull = objectEnumValues.instances.DbNull
Prisma.JsonNull = objectEnumValues.instances.JsonNull
Prisma.AnyNull = objectEnumValues.instances.AnyNull

Prisma.NullTypes = {
  DbNull: objectEnumValues.classes.DbNull,
  JsonNull: objectEnumValues.classes.JsonNull,
  AnyNull: objectEnumValues.classes.AnyNull
}



/**
 * Enums
 */

exports.Prisma.TransactionIsolationLevel = makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
});

exports.Prisma.BranchScalarFieldEnum = {
  id: 'id',
  name: 'name',
  address: 'address',
  city: 'city',
  phone: 'phone',
  email: 'email',
  isActive: 'isActive',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.ReviewScalarFieldEnum = {
  id: 'id',
  reviewText: 'reviewText',
  rating: 'rating',
  createdAt: 'createdAt',
  branchId: 'branchId'
};

exports.Prisma.BranchSentimentScalarFieldEnum = {
  id: 'id',
  sentimentScore: 'sentimentScore',
  analyzedAt: 'analyzedAt',
  branchId: 'branchId'
};

exports.Prisma.UserScalarFieldEnum = {
  id: 'id',
  authId: 'authId',
  email: 'email',
  name: 'name',
  phone: 'phone',
  role: 'role',
  isActive: 'isActive',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  branchId: 'branchId'
};

exports.Prisma.HallScalarFieldEnum = {
  id: 'id',
  name: 'name',
  capacity: 'capacity',
  pricePerEvent: 'pricePerEvent',
  amenities: 'amenities',
  isActive: 'isActive',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  branchId: 'branchId'
};

exports.Prisma.LeadScalarFieldEnum = {
  id: 'id',
  customerName: 'customerName',
  customerPhone: 'customerPhone',
  customerEmail: 'customerEmail',
  eventType: 'eventType',
  eventDate: 'eventDate',
  guestCount: 'guestCount',
  status: 'status',
  source: 'source',
  notes: 'notes',
  lostReason: 'lostReason',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  branchId: 'branchId',
  assignedToId: 'assignedToId',
  createdById: 'createdById'
};

exports.Prisma.LeadActivityScalarFieldEnum = {
  id: 'id',
  action: 'action',
  details: 'details',
  createdAt: 'createdAt',
  leadId: 'leadId',
  userId: 'userId'
};

exports.Prisma.BookingScalarFieldEnum = {
  id: 'id',
  bookingNumber: 'bookingNumber',
  startDate: 'startDate',
  endDate: 'endDate',
  startTime: 'startTime',
  endTime: 'endTime',
  guestCount: 'guestCount',
  status: 'status',
  totalAmount: 'totalAmount',
  advanceAmount: 'advanceAmount',
  balanceAmount: 'balanceAmount',
  notes: 'notes',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  branchId: 'branchId',
  hallId: 'hallId',
  leadId: 'leadId',
  createdById: 'createdById'
};

exports.Prisma.EventScalarFieldEnum = {
  id: 'id',
  eventDate: 'eventDate',
  guestCount: 'guestCount',
  status: 'status',
  notes: 'notes',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  branchId: 'branchId',
  bookingId: 'bookingId'
};

exports.Prisma.EventMenuItemScalarFieldEnum = {
  id: 'id',
  quantity: 'quantity',
  notes: 'notes',
  eventId: 'eventId',
  menuItemId: 'menuItemId'
};

exports.Prisma.EventVendorScalarFieldEnum = {
  id: 'id',
  service: 'service',
  cost: 'cost',
  notes: 'notes',
  eventId: 'eventId',
  vendorId: 'vendorId'
};

exports.Prisma.EventChecklistScalarFieldEnum = {
  id: 'id',
  task: 'task',
  status: 'status',
  dueDate: 'dueDate',
  completedAt: 'completedAt',
  eventId: 'eventId'
};

exports.Prisma.MenuItemScalarFieldEnum = {
  id: 'id',
  name: 'name',
  category: 'category',
  pricePerPlate: 'pricePerPlate',
  isVeg: 'isVeg',
  isActive: 'isActive',
  branchId: 'branchId'
};

exports.Prisma.MenuItemIngredientScalarFieldEnum = {
  id: 'id',
  quantityPerServing: 'quantityPerServing',
  unit: 'unit',
  menuItemId: 'menuItemId',
  inventoryItemId: 'inventoryItemId'
};

exports.Prisma.InventoryItemScalarFieldEnum = {
  id: 'id',
  name: 'name',
  category: 'category',
  unit: 'unit',
  currentStock: 'currentStock',
  minStockLevel: 'minStockLevel',
  costPerUnit: 'costPerUnit',
  isActive: 'isActive',
  branchId: 'branchId'
};

exports.Prisma.StockMovementScalarFieldEnum = {
  id: 'id',
  type: 'type',
  quantity: 'quantity',
  notes: 'notes',
  createdAt: 'createdAt',
  inventoryItemId: 'inventoryItemId',
  eventId: 'eventId'
};

exports.Prisma.VendorScalarFieldEnum = {
  id: 'id',
  name: 'name',
  service: 'service',
  phone: 'phone',
  email: 'email',
  address: 'address',
  isActive: 'isActive',
  branchId: 'branchId'
};

exports.Prisma.PurchaseOrderScalarFieldEnum = {
  id: 'id',
  orderNumber: 'orderNumber',
  status: 'status',
  totalAmount: 'totalAmount',
  notes: 'notes',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  branchId: 'branchId',
  vendorId: 'vendorId'
};

exports.Prisma.PurchaseOrderItemScalarFieldEnum = {
  id: 'id',
  quantity: 'quantity',
  unitPrice: 'unitPrice',
  receivedQuantity: 'receivedQuantity',
  purchaseOrderId: 'purchaseOrderId',
  inventoryItemId: 'inventoryItemId'
};

exports.Prisma.InvoiceScalarFieldEnum = {
  id: 'id',
  invoiceNumber: 'invoiceNumber',
  subtotal: 'subtotal',
  taxAmount: 'taxAmount',
  totalAmount: 'totalAmount',
  notes: 'notes',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  branchId: 'branchId',
  bookingId: 'bookingId'
};

exports.Prisma.PaymentScalarFieldEnum = {
  id: 'id',
  amount: 'amount',
  method: 'method',
  type: 'type',
  referenceNo: 'referenceNo',
  notes: 'notes',
  paidAt: 'paidAt',
  createdAt: 'createdAt',
  invoiceId: 'invoiceId',
  receivedById: 'receivedById'
};

exports.Prisma.ResourceScalarFieldEnum = {
  id: 'id',
  name: 'name',
  category: 'category',
  unit: 'unit'
};

exports.Prisma.MenuItemResourceScalarFieldEnum = {
  id: 'id',
  quantityPerGuest: 'quantityPerGuest',
  menuItemId: 'menuItemId',
  resourceId: 'resourceId'
};

exports.Prisma.BookingResourceScalarFieldEnum = {
  id: 'id',
  calculatedQty: 'calculatedQty',
  manualQty: 'manualQty',
  isManuallyEdited: 'isManuallyEdited',
  category: 'category',
  bookingId: 'bookingId',
  resourceId: 'resourceId'
};

exports.Prisma.SortOrder = {
  asc: 'asc',
  desc: 'desc'
};

exports.Prisma.QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
};

exports.Prisma.NullsOrder = {
  first: 'first',
  last: 'last'
};
exports.Role = exports.$Enums.Role = {
  OWNER: 'OWNER',
  BRANCH_MANAGER: 'BRANCH_MANAGER',
  SALES: 'SALES',
  OPERATIONS: 'OPERATIONS',
  KITCHEN: 'KITCHEN'
};

exports.LeadStatus = exports.$Enums.LeadStatus = {
  CALL: 'CALL',
  VISIT: 'VISIT',
  NEGOTIATION: 'NEGOTIATION',
  WON: 'WON',
  LOST: 'LOST'
};

exports.BookingStatus = exports.$Enums.BookingStatus = {
  TENTATIVE: 'TENTATIVE',
  CONFIRMED: 'CONFIRMED',
  CANCELLED: 'CANCELLED',
  COMPLETED: 'COMPLETED'
};

exports.EventStatus = exports.$Enums.EventStatus = {
  UPCOMING: 'UPCOMING',
  ONGOING: 'ONGOING',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED'
};

exports.ChecklistItemStatus = exports.$Enums.ChecklistItemStatus = {
  PENDING: 'PENDING',
  IN_PROGRESS: 'IN_PROGRESS',
  DONE: 'DONE'
};

exports.StockMovementType = exports.$Enums.StockMovementType = {
  PURCHASE: 'PURCHASE',
  DEDUCTION: 'DEDUCTION',
  ADJUSTMENT: 'ADJUSTMENT',
  RETURN: 'RETURN'
};

exports.PurchaseOrderStatus = exports.$Enums.PurchaseOrderStatus = {
  DRAFT: 'DRAFT',
  ORDERED: 'ORDERED',
  PARTIALLY_RECEIVED: 'PARTIALLY_RECEIVED',
  RECEIVED: 'RECEIVED',
  CANCELLED: 'CANCELLED'
};

exports.PaymentMethod = exports.$Enums.PaymentMethod = {
  CASH: 'CASH',
  CHEQUE: 'CHEQUE',
  UPI: 'UPI',
  TRANSFER: 'TRANSFER',
  CARD: 'CARD'
};

exports.PaymentType = exports.$Enums.PaymentType = {
  ADVANCE: 'ADVANCE',
  PARTIAL: 'PARTIAL',
  FINAL: 'FINAL',
  REFUND: 'REFUND'
};

exports.ResourceCategory = exports.$Enums.ResourceCategory = {
  STAFF: 'STAFF',
  FURNITURE: 'FURNITURE',
  FOOD: 'FOOD',
  OTHER: 'OTHER'
};

exports.Prisma.ModelName = {
  Branch: 'Branch',
  Review: 'Review',
  BranchSentiment: 'BranchSentiment',
  User: 'User',
  Hall: 'Hall',
  Lead: 'Lead',
  LeadActivity: 'LeadActivity',
  Booking: 'Booking',
  Event: 'Event',
  EventMenuItem: 'EventMenuItem',
  EventVendor: 'EventVendor',
  EventChecklist: 'EventChecklist',
  MenuItem: 'MenuItem',
  MenuItemIngredient: 'MenuItemIngredient',
  InventoryItem: 'InventoryItem',
  StockMovement: 'StockMovement',
  Vendor: 'Vendor',
  PurchaseOrder: 'PurchaseOrder',
  PurchaseOrderItem: 'PurchaseOrderItem',
  Invoice: 'Invoice',
  Payment: 'Payment',
  Resource: 'Resource',
  MenuItemResource: 'MenuItemResource',
  BookingResource: 'BookingResource'
};

/**
 * This is a stub Prisma Client that will error at runtime if called.
 */
class PrismaClient {
  constructor() {
    return new Proxy(this, {
      get(target, prop) {
        let message
        const runtime = getRuntime()
        if (runtime.isEdge) {
          message = `PrismaClient is not configured to run in ${runtime.prettyName}. In order to run Prisma Client on edge runtime, either:
- Use Prisma Accelerate: https://pris.ly/d/accelerate
- Use Driver Adapters: https://pris.ly/d/driver-adapters
`;
        } else {
          message = 'PrismaClient is unable to run in this browser environment, or has been bundled for the browser (running in `' + runtime.prettyName + '`).'
        }

        message += `
If this is unexpected, please open an issue: https://pris.ly/prisma-prisma-bug-report`

        throw new Error(message)
      }
    })
  }
}

exports.PrismaClient = PrismaClient

Object.assign(exports, Prisma)
